Allow space mirror_dir better process tracking

diff --git a/n4d-lliurex-mirror.install/usr/bin/domirror b/n4d-lliurex-mirror.install/usr/bin/domirror
--- a/n4d-lliurex-mirror.install/usr/bin/domirror
+++ b/n4d-lliurex-mirror.install/usr/bin/domirror
@@ -97,7 +97,7 @@ while test -n "$1"; do
 done
 
 config_used=
-if [ ! $config_file ]; then
+if [ -z "$config_file" ]; then
     if [ -f /etc/apt/mirror.list ]; then
         config_used=/etc/apt/mirror.list
     else
@@ -105,8 +105,8 @@ if [ ! $config_file ]; then
         exit 1
     fi
 else
-    if [ -f $config_file ];then
-        config_used=$config_file
+    if [ -f "$config_file" ];then
+        config_used="$config_file"
     else
         echo "Provided config file not found"
         exit 1
@@ -152,28 +152,34 @@ if [ -z "${GPG}" -o ! -f "$GPG" ];then
     echo "gpg not found, install gpg first!, unable to continue"
     exit 1
 fi
-MIRROR_DIR=$(cat $config_used |sed -r '/\s*\S+\s+base_path\s+\S+/!d'|sed -r 's@\s*\S+\s+\S+\s+(\S+)@\1@g')
+PERL=$(which perl)
+if [ -z "${PERL}" -o ! -f "$PERL" ];then
+    echo "perl not found, install perl first!, unable to continue"
+    exit 1
+fi
+MIRROR_DIR="$(sed -r "/\s*\S+\s+base_path\s+\S+/!d; s@\s*\S+\s+\S+\s+(\S+)@\1@g" "$config_used")"
+MIRROR_DIR=$(echo $MIRROR_DIR | tr -d "\"'")
 if [ -z "$MIRROR_DIR" ];then
     echo "Unable to read MIRROR_DIR"
     exit 1
 fi
-if [ ! -d $MIRROR_DIR ]; then
+if [ ! -d "$MIRROR_DIR" ]; then
     mkdir -p $MIRROR_DIR
 fi
-MIRROR_DIR=$($REALPATH $MIRROR_DIR)
-VAR_DIR=$(cat $config_used |sed -r '/\s*\S+\s+var_path\s+\S+/!d'|sed -r 's@\s*\S+\s+\S+\s+(\S+)@\1@g'|sed "s@\$base_path@$MIRROR_DIR@g")
-if [ ! -d $VAR_DIR ]; then
-    mkdir -p $VAR_DIR
+MIRROR_DIR=$($REALPATH "$MIRROR_DIR")
+VAR_DIR="$(sed -r "/\s*\S+\s+var_path\s+\S+/!d; s@\s*\S+\s+\S+\s+(\S+)@\1@g; s@\\\$base_path@$MIRROR_DIR@g" "$config_used")"
+if [ ! -d "$VAR_DIR" ]; then
+    mkdir -p "$VAR_DIR"
 fi
-ALL_FILE=$VAR_DIR/ALL
-SIG_DIR=$VAR_DIR
+ALL_FILE="$VAR_DIR/ALL"
+SIG_DIR="$VAR_DIR"
 # DEFAULT FILE CHECKING METHOD
 SIGFILES="MD5"
 KEYRING=/etc/apt/trusted.gpg.d/lliurex-archive-keyring-gpg.gpg
 KEYRINGS=$(find /etc/apt -type f -name '*.gpg')
-OLD_DIR=$MIRROR_DIR/old
+OLD_DIR="$MIRROR_DIR/old"
 if [ -n "$incremental" ];then
-    mkdir -p $OLD_DIR
+    mkdir -p "$OLD_DIR"
 fi
 
 make_temps(){
@@ -188,8 +194,8 @@ trap badthings SIGUSR1
 badthings(){
     echo Killing $SON
     if [ -z "$gets" ]; then
-    echo Nothing to kill
-    return
+        echo Nothing to kill
+        return
     fi
     for x in $gets; do 
         kill -9 $x &> /dev/null
@@ -200,52 +206,54 @@ badthings(){
 
 run(){
     make_link
-    if [ $config_file ];then
-        $($APTMIRROR $config_file &>/dev/null &)
+    if [ -n "$config_file" ];then
+        $(nice -n5 $APTMIRROR "$config_file" &>/dev/null &)
     else
-        $($APTMIRROR &>/dev/null &)
+        $(nice -n5 $APTMIRROR &>/dev/null &)
     fi
     pid=$($PGREP -P $ME||true)
+    $PGREP -P $ME
 }
 
 getpids(){
-    pid=$($PGREP -f apt-mirror||true)
+    pid=$($PGREP -f "$PERL $APTMIRROR"||true)
+    gets=""
     if [ -n "$pid" ];then
-        gets=$($PGREP -P $pid -f wget||true)
-    else
-        gets=""
-    fi
+        for p in $pid; do       
+            gets="$gets $($PGREP -P $pid -f wget||true)"
+        done;
+    fi;
 }
 
 make_link(){
     if [ -d "$MIRROR_DIR/pool" -a ! -L "$MIRROR_DIR/pool" ]; then
-        mkdir -p $MIRROR_DIR/lliurex.net/$DISTRO
-        mv $MIRROR_DIR/pool $MIRROR_DIR/lliurex.net/$DISTRO
+        mkdir -p "$MIRROR_DIR/lliurex.net/$DISTRO"
+        mv "$MIRROR_DIR/pool" "$MIRROR_DIR/lliurex.net/$DISTRO"
     fi
     if [ ! -L "$MIRROR_DIR/pool" ];then
-        POOL=$(find $MIRROR_DIR -type d -not -path '*/skel/*' -name 'pool' -print)
+        POOL=$(find "$MIRROR_DIR" -type d -not -path '*/skel/*' -name 'pool' -print)
         if [ -n "$POOL" ]; then
-            if [ "$(echo $POOL|tr '\n' ' '| wc -w)" -gt 1 ];then
-                POOL=$(echo $POOL|tr '\n' ' '|tr ' ' '\n'|grep lliurex)
+            if [ "$(echo "$POOL"|tr '\n' ' '| wc -w)" -gt 1 ];then
+                POOL=$(echo "$POOL"|tr '\n' ' '|tr ' ' '\n'|grep lliurex)
             fi
-            rp="$($REALPATH --relative-to=$MIRROR_DIR $POOL)"
+            rp="$($REALPATH --relative-to="$MIRROR_DIR" "$POOL")"
             if [ -n "$rp" ];then
-                ln -s $rp $MIRROR_DIR/pool
+                ln -s "$rp" "$MIRROR_DIR/pool"
             fi
         fi
     fi
     if [ -d "$MIRROR_DIR/dists" -a ! -L "$MIRROR_DIR/dists" ];then
-        mv $MIRROR_DIR/dists $MIRROR_DIR/old_dists
+        mv "$MIRROR_DIR/dists" "$MIRROR_DIR/old_dists"
     fi
     if [ ! -L "$MIRROR_DIR/dists" ];then
-        DISTS=$(find $MIRROR_DIR -type d -path '*/skel/*' -name 'dists' -print)
+        DISTS=$(find "$MIRROR_DIR" -type d -path '*/skel/*' -name 'dists' -print)
         if [ -n "$DISTS" ]; then
-            if [ "$(echo $DISTS|tr '\n' ' '|wc -w)" -gt 1 ];then
-                DISTS=$(echo $DISTS|tr '\n' ' '|tr ' ' '\n'|grep lliurex)
+            if [ "$(echo "$DISTS"|tr '\n' ' '|wc -w)" -gt 1 ];then
+                DISTS=$(echo "$DISTS"|tr '\n' ' '|tr ' ' '\n'|grep lliurex)
             fi
-            rp="$($REALPATH --relative-to=$MIRROR_DIR $DISTS)"
+            rp="$($REALPATH --relative-to="$MIRROR_DIR" "$DISTS")"
             if [ -n "$rp" ];then
-                ln -s $rp $MIRROR_DIR/dists
+                ln -s "$rp" "$MIRROR_DIR/dists"
             fi
         fi
     fi
@@ -256,44 +264,50 @@ calcule(){
     if [ -z "$TMP_CURRENT" -o -z "$TMP_ALL" ];then
         make_temps
     fi
-    if [ -f $ALL_FILE ]; then
+    if [ -f "$ALL_FILE" ]; then
         retry=2
         while [ $retry -gt 0 ]; do
-            asize1=$(echo $(ls -s $ALL_FILE |cut -d/ -f1))
+            asize1=$(echo $(ls -s "$ALL_FILE" |cut -d/ -f1))
             sleep 1
-            asize2=$(echo $(ls -s $ALL_FILE |cut -d/ -f1))
+            asize2=$(echo $(ls -s "$ALL_FILE" |cut -d/ -f1))
             retry=$(($retry-1))
         done
         if [ -n "$asize1" -a "x$asize1" != "x$asize2" ]; then
             return $OLD_PERCENT
         fi
-        cat $ALL_FILE |sort|uniq > $TMP_ALL
-        find $MIRROR_DIR -type f \( -not -path '*/old/*' -not -path '*/var/*' -not -path '*/skel/*' -not -path '*/dists/*' \) -print |grep -v time-of-last-update|sort|uniq|sed -E 's@.*(lliurex\.net)(.*)@\1\2@' > $TMP_CURRENT
-        old=$($COMM -23 $TMP_CURRENT $TMP_ALL)
-        mirror_dir_len=$(($(echo $MIRROR_DIR | wc -c)-1))
-        if [ -n "$incremental" ]; then
-            if [ -n "$old" ];then
-                for x in $old; do
-                    dn=$($DIRNAME $x)
-                    bn=$($BASENAME $x)
-                    mkdir -p $OLD_DIR/$dn
-                    mv $MIRROR_DIR/$x $OLD_DIR/$dn/$bn
-                done
-            fi
-        else
-            echo $old | xargs -n1 | while read file; do
-                rp=$(realpath -e $MIRROR_DIR/$file >/dev/null 2>&1)
+        cat "$ALL_FILE" |sort|uniq > $TMP_ALL
+        first_dir=$(head -1 "$ALL_FILE" | cut -d'/' -f1)
+        find "$MIRROR_DIR" -type f \( -iname '*.deb' -not -path '*/old/*' -not -path '*/var/*' -not -path '*/skel/*' -not -path '*/dists/*' \) -print |grep -v time-of-last-update|sed -E "s@.*($first_dir)(.*)@\1\2@" |sort|uniq > $TMP_CURRENT
+        declare -a old
+        readarray -d $'\0' old < <($COMM -23 $TMP_CURRENT $TMP_ALL|tr '\n' '\0')
+        mirror_dir_len=$(($(echo "$MIRROR_DIR" | wc -c)-1))
+        mirror_next_path_len=$(($mirror_dir_len+2))
+        
+        # move (incremental) or delete (not incremental, (default)) old files
+        if [ "${#old[@]}" -gt 0 ];then
+            for file in "${old[@]}"; do
+                rp=$(realpath -e "$file" >/dev/null 2>&1)
                 if [ $? -eq 0 -a -n "$mirror_dir_len" -a "x0" != "x$mirror_dir_len" ]; then
-                    tmp=$(echo $MIRROR_DIR/$file|cut -c -$mirror_dir_len)
-                    if [ -n "$tmp" ]; then
-                        if [ "x$tmp" == "x$MIRROR_DIR" -a -f $MIRROR_DIR/$file ];then
-                            rm $MIRROR_DIR/$file
+                    start_of_file=$(echo "$file"|cut -c -$mirror_dir_len)
+                    continuation_of_file=$(echo "$file"|cut -c $mirror_next_path_len-)
+                    if [ -n "$continuation_of_file" -a -n "$start_of_file" ];then
+                        start_of_continuation=$(echo $continuation_of_file|cut -c -$(( $(echo $first_dir|wc -c)+1 )) )
+                        if [ "x$start_of_file" == "x$MIRROR_DIR" -a -f "$file" -a "x$first_dir" ==  "x$start_of_continuation" ];then
+                            if [ -n "$incremental "];then
+                                dn=$($DIRNAME "$x")
+                                bn=$($BASENAME "$x")
+                                mkdir -p "$OLD_DIR/$dn"
+                                mv "$x" "$OLD_DIR/$dn/$bn"
+                            else
+                                rm "$file"
+                            fi
                         fi
                     fi
                 fi
             done
         fi
-        find $MIRROR_DIR -type f \( -not -path '*/old/*' -not -path '*/var/*' -not -path '*/skel/*' -not -path '*/dists/*' \) -print |grep -v time-of-last-update|sort|uniq|sed -E 's@.*(lliurex\.net)(.*)@\1\2@' > $TMP_CURRENT
+    
+        find "$MIRROR_DIR" -type f \( -iname '*.deb' -not -path '*/old/*' -not -path '*/var/*' -not -path '*/skel/*' -not -path '*/dists/*' \) -print |grep -v time-of-last-update|sed -E 's@.*(lliurex\.net)(.*)@\1\2@' |sort|uniq > $TMP_CURRENT
         ncurrent=$(cat $TMP_CURRENT|wc -l)
         nall=$(cat $TMP_ALL|wc -l)
         if [ -n "$nall" -a -n "$ncurrent" -a $ncurrent -gt 0 -a $nall -ge $ncurrent ]; then
@@ -330,14 +344,15 @@ fi
 
 if [ $verify ]; then
     echo "Verifying mirror"
-    find $MIRROR_DIR -type f -name InRelease \( -not -path '*/var/*' -not -path '*/skel/*' -not -path '*/old/*' \) | while read file; do
+    find "$MIRROR_DIR" -type f -name InRelease \( -not -path '*/var/*' -not -path '*/skel/*' -not -path '*/old/*' \) | while read file; do
         valid=0
         for kring in $KEYRINGS; do
-            if $GPG --keyring $kring --verify $file  &> /dev/null; then
+            if $GPG --keyring "$kring" --verify "$file" &> /dev/null ; then
                 valid=1
+                break
             fi
         done;
-        if [ ! $valid ];then
+        if [ $valid -eq 0 ];then
             echo "Failed file verification $file"
         fi
     done;
@@ -352,7 +367,7 @@ if [ $verify ]; then
                     echo "sha1sum not found, install coreutils first!, skipping verify process"
                 else
                     if [ -f "$VAR_DIR/$t" ]; then
-                        ret1=$(cd $MIRROR_DIR;LANG=C sha1sum --quiet -c $VAR_DIR/$t 2>/dev/null|sed -E 's/([^:]+):\s+FAILED/\1/g')
+                        ret1=$(cd "$MIRROR_DIR";LANG=C sha1sum --quiet -c "$VAR_DIR/$t" 2>/dev/null|sed -E 's/([^:]+):\s+FAILED/\1/g')
                     else
                         echo "skipping $t checking, sumfile not available"
                     fi
@@ -364,7 +379,7 @@ if [ $verify ]; then
                     echo "sha256sum not found, install coreutils first!, skipping verify process"
                 else
                     if [ -f "$VAR_DIR/$t" ]; then
-                        ret2=$(cd $MIRROR_DIR;LANG=C sha256sum --quiet -c $VAR_DIR/$t 2>/dev/null|sed -E 's/([^:]+):\s+FAILED/\1/g')
+                        ret2=$(cd "$MIRROR_DIR";LANG=C sha256sum --quiet -c "$VAR_DIR/$t" 2>/dev/null|sed -E 's/([^:]+):\s+FAILED/\1/g')
                     else
                         echo "skipping $t checking, sumfile not available"
                     fi
@@ -376,7 +391,7 @@ if [ $verify ]; then
                     echo "md5sum not found, install coreutils first!, skipping verify process"
                 else
                     if [ -f "$VAR_DIR/$t" ]; then
-                        ret3=$(cd $MIRROR_DIR;LANG=C md5sum --quiet -c $VAR_DIR/$t 2>/dev/null|sed -E 's/([^:]+):\s+FAILED/\1/g')
+                        ret3=$(cd "$MIRROR_DIR";LANG=C md5sum --quiet -c "$VAR_DIR/$t" 2>/dev/null|sed -E 's/([^:]+):\s+FAILED/\1/g')
                     else
                         echo "skipping $t checking, sumfile not available"
                     fi
@@ -411,9 +426,9 @@ if [ $verify ]; then
             for x in $ret1; do
                 if [ -f "$MIRROR_DIR/$x" ];then
                     if [ -n "$incremental" ];then
-                        mv $MIRROR_DIR/$x $MIRROR_DIR/$x.failed
+                        mv "$MIRROR_DIR/$x" "$MIRROR_DIR/$x.failed"
                     else
-                        rm $MIRROR_DIR/$x
+                        rm "$MIRROR_DIR/$x"
                     fi
                     nretry=$(($nretry+1))
                 fi
@@ -421,9 +436,9 @@ if [ $verify ]; then
             for x in $ret2; do
                 if [ -f "$MIRROR_DIR/$x" ];then
                     if [ -n "$incremental" ];then
-                        mv $MIRROR_DIR/$x $MIRROR_DIR/$x.failed
+                        mv "$MIRROR_DIR/$x" "$MIRROR_DIR/$x.failed"
                     else
-                        rm $MIRROR_DIR/$x
+                        rm "$MIRROR_DIR/$x"
                     fi
                     nretry=$(($nretry+1))
                 fi
@@ -431,9 +446,9 @@ if [ $verify ]; then
             for x in $ret3; do
                 if [ -f "$MIRROR_DIR/$x" ];then
                     if [ -n "$incremental" ];then
-                        mv $MIRROR_DIR/$x $MIRROR_DIR/$x.failed
+                        mv "$MIRROR_DIR/$x" "$MIRROR_DIR/$x.failed"
                     else
-                        rm $MIRROR_DIR/$x
+                        rm "$MIRROR_DIR/$x"
                     fi
                     nretry=$(($nretry+1))
                 fi
@@ -445,13 +460,13 @@ if [ $verify ]; then
             if [ -f $TMP_ALL ]; then
                 rm $TMP_ALL
             fi
-            exec bash $0 --config-file=$config_used
+            exec bash $0 --config-file="$config_used"
         fi
     fi
 fi
 last_update="$(wget -q http://lliurex.net/$DISTRO/time-of-last-update -O -)"
 if [ -n "$last_update" ]; then
-    echo $last_update > $MIRROR_DIR/time-of-last-update
+    echo $last_update > "$MIRROR_DIR/time-of-last-update"
 else
     echo "WARNING! Can't download time-of-last-update file"
 fi
